sudo: false
dist: trusty
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - typings/globals
#after_success:
#  - npm run deploy
deploy:
  provider: releases
  api_key: $API_KEY
  file: './dist'
  on:
    repo: chris-ramon/dashboard
