sudo: false
dist: trusty
language: node_js
node_js:
  - "6"
#script: npm run coveralls
branches:
 only:
   - "master"
cache:
  directories:
  - node_modules
  - typings/globals

#after_success:
#    - npm run deploy
deploy:
    provider: script
    script: scripts/prod-deploy.sh
    on:
        repo: chris-ramon/dashboard
        tags: true
        all_branches: true
