#!/usr/bin/env bash
set -e # halt script on error

# Copy over the generated code to the harness
cp -R dist/. harness/.

# For master branch, we push to the dev location
# Not on master, we push to a build location
if [[ $TRAVIS_PULL_REQUEST ]]; then
  echo Deploying to Build Dashboard
  firebase use build
else
  echo Deploying to Dev Dashboard
  firebase use default
fi

# And deploy the harness directory
firebase deploy --token "$FIREBASE_TOKEN"